### ISSUE TITLE
error while running script on vivado 2014.4

### ISSUE THREAD

**Issue by patrickpoirier51** [Digilent/Arty#2] opened 2016-01-27 00:53 UTC
## create_root_design ""

ERROR: [IP_Flow 19-3461] Value 'shield_dp0_dp19' is out of the range for parameter 'GPIO BOARD INTERFACE(GPIO_BOARD_INTERFACE)' for BD Cell '/axi_gpio_0' . Valid values are - Custom, dip_switches_4bits, i2c_pullups, led_4bits, push_buttons_4bits, rgb_led
INFO: [IP_Flow 19-3438] Customization errors found on '/axi_gpio_0'. Restoring to previous valid configuration.
INFO: [Common 17-17] undo 'set_property'
ERROR: [Common 17-39] 'set_property' failed due to earlier errors.

```
while executing
```

"rdi::add_properties -dict {CONFIG.C_GPIO_WIDTH 20 CONFIG.C_INTERRUPT_PRESENT 1 CONFIG.GPIO_BOARD_INTERFACE shield_dp0_dp19 CONFIG.USE_BOARD_FLOW true}..."
    invoked from within
"set_property -dict [ list  CONFIG.C_GPIO_WIDTH {20}  CONFIG.C_INTERRUPT_PRESENT {1}  CONFIG.GPIO_BOARD_INTERFACE {shield_dp0_dp19}  CONFIG.USE_BOARD_F..."
    (procedure "create_root_design" line 71)
    invoked from within
"create_root_design """
    (file "../src/bd/system.tcl" line 898)

```
while executing
```

"source $origin_dir/src/bd/system.tcl"
    (file "./create_project.tcl" line 103)

**Comment by tom21091** [comment] 2016-01-27 19:01
This is caused because we have not updated the old board files for Vivado 2014.X. This script should work fine with newer versions of Vivado. I'll look into updating the old board files.

**Comment by patrickpoirier51** [comment] 2016-01-27 19:23
Ok
Please note that the wiki ( arty:basedesign)  explicitly requires that we use 2015.4 , (sorry  I mistype the ivrtsion on the message)

**Comment by sbobrowicz** [comment] 2016-01-27 20:06
Turns out the version check was disabled, so I re-enabled it to prevent people from using the wrong version. I will correct the wiki, thanks for pointing that out. Technically it should have worked in 2015.4 though (see my commit message [a0130077b4c63106c384e9a6302afc9ef4d02d7f](https://github.com/Digilent/Arty/commit/a0130077b4c63106c384e9a6302afc9ef4d02d7f)). Did you install the most recent board files before building the project? The problem you are describing shouldn't be fixed by switching to 2015.3, but likely is caused by not using the board files that include recent fixes.

**Comment by patrickpoirier51** [comment] 2016-01-27 20:20
OK I will make sure that I got the latest board files, rebuild and give an update.

Thanks Sam, appreciate that you get involve with resolving Arty, hopefully we'll get the Microblaze working as well :+1

**Comment by sbobrowicz** [comment] 2016-01-29 21:29
Looks like it's working as reported in your forum post. Closing this issue

**Closed as completed by sbobrowicz** 2016-01-29 21:29 UTC
